apiVersion: v1
kind: ConfigMap
metadata:
  name: my-scheduler-config
  namespace: kube-system
data:
  my-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    clientConnection:
      kubeconfig: "/var/run/kubernetes/scheduler.kubeconfig"
    extenders:   
      - urlPrefix: "http://localhost:8888/" 
        filterVerb: "filter" 
        prioritizeVerb: "prioritize" 
        weight: 1
        enableHTTPS: false

